/*******************************************************************************
 * Copyright (C)  2015 - 2016  Carnegie Mellon University
 * Author: Oliver Ferschke
 *
 * This file is part of DiscourseDB.
 *
 * DiscourseDB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * DiscourseDB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DiscourseDB.  If not, see <http://www.gnu.org/licenses/> 
 * or write to the Free Software Foundation, Inc., 51 Franklin Street, 
 * Fifth Floor, Boston, MA 02110-1301  USA
 *******************************************************************************/
package edu.cmu.cs.lti.discoursedb.io.edx.forum.model;

import lombok.Data;

/**
 * POJO for the user info in *-auth_user-prod-analytics.sql files.
 * Boilerplate code (getters/setters etc) will be autogenerated by Lombok.
 * 
 * @author Oliver Ferschke
 *
 */
@Data
public class UserInfo {
	
	private String id;      
	private String username;        
	private String first_name;      
	private String last_name;       
	private String email;
	private String password;        
	private String is_staff;        
	private String is_active;       
	private String is_superuser;    
	private String last_login;      
	private String date_joined;     
	private String status;  
	private String email_key;       
	private String avatar_type;     
	private String country; 
	private String show_country;    
	private String date_of_birth;   
	private String interesting_tags;        
	private String ignored_tags;    
	private String email_tag_filter_strategy;       
	private String display_tag_filter_strategy;     
	private String consecutive_days_visit_count;
	
}
