package edu.cmu.cs.lti.discoursedb.io.bazaar.model;

import lombok.Data;

/**
 * POJO for the message information.
 * 
 * Boilerplate code will be autogenerated by Lombok at compile time. 
 * 
 * @author Haitian Gong
 * @author Oliver Ferschke
 *
 */
@Data
public class Message {
	
	private String roomid;
	private String id;
	private String created_time;
	private String type;
	private String content;
	private String username;
	private String parentid;
	private String useraddress;
	
}
