package edu.cmu.cs.lti.discoursedb.io.bazaar.model;

import lombok.Data;

/**
 * POJO for the room information.
 * 
 * Boilerplate code will be autogenerated by Lombok at compile time
 * 
 * @author Haitian Gong
 * @author Oliver Ferschke
 *
 */
@Data
public class Room {
	
	private String id;
	private String name;
	private String created_time;
	private String modified_time;
	private String comment;

}
