/*******************************************************************************
 * Copyright (C)  2015 - 2016  Carnegie Mellon University
 * Author: Oliver Ferschke
 *
 * This file is part of DiscourseDB.
 *
 * DiscourseDB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * DiscourseDB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DiscourseDB.  If not, see <http://www.gnu.org/licenses/> 
 * or write to the Free Software Foundation, Inc., 51 Franklin Street, 
 * Fifth Floor, Boston, MA 02110-1301  USA
 *******************************************************************************/
package edu.cmu.cs.lti.discoursedb.io.habworlds.model;

import lombok.Data;

/**
 * POJO representing a post in habworlds.
 * 
 * Boilerplate code will be auto-generated by Lombok at compile time. 
 * 
 * @author Haitian Gong
 *
 */

@Data
public class HabWorldPost {
	
	private int InteractionID;
	private String sessionID;
	private int userID;
	private int tutorialSessionID;
	private int tutorialID;
	private int activityID;
	private String questionID;
	private int attempt;
	private int questionResult;
	private int questionScore;
	private String serverTime;
	private String snapshot;
	private String trapStateID;
	private int tutorialAttempt;
	private String sequenceId;

}
