/*******************************************************************************
 * Copyright (C)  2015 - 2016  Carnegie Mellon University
 * Author: Oliver Ferschke
 *
 * This file is part of DiscourseDB.
 *
 * DiscourseDB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * DiscourseDB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DiscourseDB.  If not, see <http://www.gnu.org/licenses/> 
 * or write to the Free Software Foundation, Inc., 51 Franklin Street, 
 * Fifth Floor, Boston, MA 02110-1301  USA
 *******************************************************************************/
package edu.cmu.cs.lti.discoursedb.io.tags.model;

import lombok.Data;

/**
 * POJO to represents twitter data collected by TAG v6.0.
 * 
 * Boilerplate code will be generated by Lombok at compile time.
 * 
 * @author Haitian Gong
 * @author Oliver Ferschke
 *
 */
@Data
public class TweetInfo {
	
	private String id_str;
	private String from_user;
	private String text;
	private String created_at;
	private String time;
	private String geo_coordinates;
	private String user_lang;
	private String in_reply_to_user;
	private String in_reply_to_screen_name;
	private String from_user_id_str;
	private String in_reply_to_user_id_str;
	private String in_reply_to_status_id_str;
	private String source;
	private String profile_image_url;
	private String user_followers_count;
	private String user_friends_count;
	private String user_utc_offset;
	private String status_url;
	private String entities_str;	
}
